flask-wtf-crud-websocket/app/models.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'
__blog__ = u'http://www.os373.cn'

from . import db


class User(db.Model):
    '''Example for crud
    以用户为例，来展示 CRUD 操作！
    '''
    __tablename__ = 'crud'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    email = db.Column(db.String(64), unique=True, index=True)
    status = db.Column(db.Boolean, default=False)
    role = db.Column(db.Boolean, default=False)

    def to_json(self):
        return {"id": self.id, "username": self.username, "email": self.email, "status": self.status, "role": self.role}

    def __repr__(self):
        return '<User %r>' % self.username

flask-wtf-crud-websocket/app/crud/forms.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'
__blog__ = u'http://www.os373.cn'

from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField
from wtforms.validators import DataRequired, Length, Email, Regexp
from wtforms import ValidationError
from ..models import User


class AddUserForm(FlaskForm):
    username = StringField(u'用户名', validators=[DataRequired(), Length(1, 64, message=u'姓名长度要在1和64之间'),
                       Regexp(ur'^[\u4E00-\u9FFF]+$', flags=0, message=u'用户名必须为中文')])
    email = StringField(u'邮箱', validators=[DataRequired(), Length(6, 64, message=u'邮件长度要在6和64之间'),
                        Email(message=u'邮件格式不正确！')])
    role = SelectField(u'权限', choices=[(u'True', u'管理员'), (u'False', u'一般用户') ])
    status = SelectField(u'状态', choices=[(u'True', u'正常'), (u'False', u'注销') ])
    submit = SubmitField(u'添加用户')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError(u'用户名已被注册！')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError(u'邮箱已被注册！')


class DeleteUserForm(FlaskForm):
    user_id = StringField()


class EditUserForm(FlaskForm):
    username = StringField(u'用户名', validators=[DataRequired(), Length(1, 64, message=u'姓名长度要在1和64之间'),
                       Regexp(ur'^[\u4E00-\u9FFF]+$', flags=0, message=u'用户名必须为中文')])
    email = StringField(u'邮箱', validators=[DataRequired(), Length(6, 64, message=u'邮件长度要在6和64之间'),
                        Email(message=u'邮件格式不正确！')])
    role = SelectField(u'权限', choices=[(u'True', u'管理员'), (u'False', u'一般用户') ])
    status = SelectField(u'状态', choices=[(u'True', u'正常'), (u'False', u'注销')])
    submit = SubmitField(u'修改用户')

flask-wtf-crud-websocket/app/__init__.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'
__blog__ = u'http://www.os373.cn'

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config
from flask_socketio import SocketIO
db = SQLAlchemy()

async_mode = None
socketio = SocketIO()


def create_app(config_name):
    """ 使用工厂函数初始化程序实例"""
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app=app)

    db.init_app(app=app)

    socketio.init_app(app=app, async_mode=async_mode)

    # 注册蓝本crud
    from .crud import crud as crud_blueprint
    app.register_blueprint(crud_blueprint, url_prefix='/crud')

    return app

flask-wtf-crud-websocket/app/crud/__init__.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'
__blog__ = u'http://www.os373.cn'


from flask import Blueprint


crud = Blueprint('crud', __name__, template_folder="templates", static_url_path='', static_folder='templates/static')

# 在末尾导入相关模块，是为了避免循环导入依赖，因为在下面的模块中还要导入蓝本main
from . import views

flask-wtf-crud-websocket/app/crud/views.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'
__blog__ = u'http://www.os373.cn'

from flask import render_template, redirect, request, current_app, url_for, flash, json
from . import crud
from ..models import User
from .forms import AddUserForm, DeleteUserForm, EditUserForm
from ..import db
from threading import Lock
from app import socketio
from flask_socketio import emit


thread = None
thread_lock = Lock()


def background_thread(users_to_json):
    """Example of how to send server generated events to clients."""
    while True:
        socketio.sleep(5)

        socketio.emit('user_response', {'data': users_to_json}, namespace='/websocket/user_refresh')


@crud.route('/', methods=['GET', 'POST'])
def index():

    return render_template('index.html')


@crud.route('/websocket', methods=['GET', 'POST'])
def websocket():
    add_user_form = AddUserForm(prefix='add_user')
    delete_user_form = DeleteUserForm(prefix='delete_user')
    if add_user_form.validate_on_submit():
        if add_user_form.role.data == u'True':
            role = True
        else:
            role = False
        if add_user_form.status.data == u'True':
            status = True
        else:
            status = False
        u = User(username=add_user_form.username.data.strip(), email=add_user_form.email.data.strip(),
                 role=role, status=status)
        db.session.add(u)
        flash({'success': u'添加用户<%s>成功！' % add_user_form.username.data.strip()})
    if delete_user_form.validate_on_submit():
        u = User.query.get_or_404(int(delete_user_form.user_id.data.strip()))
        db.session.delete(u)
        flash({'success': u'删除用户<%s>成功！' % u.username})

    users = User.query.all()

    return render_template('websocket.html', users=users, addUserForm=add_user_form, deleteUserForm=delete_user_form)


@crud.route('/websocket-edit/<user_id>', methods=['GET', 'POST'])
def user_edit(user_id):
    user = User.query.get_or_404(user_id)
    edit_user_form = EditUserForm(prefix='edit_user', obj=user)
    if edit_user_form.validate_on_submit():
        user.username = edit_user_form.username.data.strip()
        user.email = edit_user_form.email.data.strip()
        if edit_user_form.role.data == u'True':
            user.role = True
        else:
            user.role = False
        if edit_user_form.status.data == u'True':
            user.status = True
        else:
            user.status = False
        flash({'success': u'用户资料已修改成功！'})
        return redirect(url_for('.websocket'))

    return render_template('edit_websocket.html', editUserForm=edit_user_form, user=user)


@socketio.on('connect', namespace='/websocket/user_refresh')
def connect():
    global thread
    with thread_lock:
        users = User.query.all()
        users_to_json = [user.to_json() for user in users]

        if thread is None:
            thread = socketio.start_background_task(background_thread, (users_to_json, ))
    emit('server_response', {'data': '试图连接客户端！'})


@socketio.on('connect_event', namespace='/websocket/user_refresh')
def refresh_message(message):

    emit('server_response', {'data': message['data']})

flask-wtf-crud-websocket/app/crud/templates/common/alert.html
<!-- flash提示 -->
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                {% if message['success'] %}
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>成功:</strong> {{ message['success'] }}
                    </div>
                {% elif message['error'] %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>错误：</strong> {{ message['error'] }}
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
<!-- flash提示 end -->

flask-wtf-crud-websocket/app/crud/templates/common/base.html
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="{% block desc %}谦卑并倔强的活着！{% endblock %}">
        <meta name="author" content="">
        <link rel="icon" href="{{ url_for('crud.static', filename='images/favicon.ico')}}">

        <title>{% block title %}藕丝空间{% endblock %}</title>
        {% block css %}
            <!-- 新 Bootstrap 核心 CSS 文件 -->
            <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">

            <!-- 可选的Bootstrap主题文件（一般不用引入） -->
            <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
            <!-- 个性化主题文件 -->
            <link href="{{ url_for('crud.static', filename='css/crud.css')}}" rel="stylesheet">

        {% endblock %}

        {% block js %}
            <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
            <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>

            <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
            <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

            <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js"></script>

            <!-- 个性化 js 文件 -->
            <script src="{{ url_for('crud.static', filename='js/crud.js')}}"></script>
        {% endblock %}
    </head>

    <body>
        {% include 'common/header.html' %}
        <div class="container">
            <div class="row row-offcanvas row-offcanvas-right">
                <div class="col-xs-12 col-sm-8">
                    <p class="pull-right visible-xs">
                        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">导航</button>
                    </p>
                    <div class="row">
                        {% block content %}
                        {% endblock %}
                    </div><!--/row-->
                </div><!--/.col-xs-12.col-sm-9-->
                {% include 'common/sidebar.html' %}
            </div><!--/row-->
            {% include 'common/footer.html' %}
        </div><!--/.container-->
    </body>
</html>

flask-wtf-crud-websocket/app/crud/templates/common/footer.html
<hr>

<footer>
    <div class="col-xs-12">
        <div class="col-xs -12 col-sm-4">
            <p>Powered by <a href="http://www.os373.cn">Pyblog</a></p>
            <p><a href="#">管理页面</a></p>
        </div>
        <div class="col-xs -12 col-sm-4">
            <p><a href="mailto:xxxxxxxxxxxxxx@gmail.com"><i class="glyphicon glyphicon-envelope"></i> xxxxxxxxxxx@gmail.com </a></p>
            <p><a href="http://www.miibeian.gov.cn/" target="_blank">豫ICP备xxxxxxxxxxxxx号</a></p>
        </div>
        <div class="col-xs -12 col-sm-4">
            <p class="pull-right"><a href="#">回到顶部</a></p>
        </div>
    </div>
</footer>

flask-wtf-crud-websocket/app/crud/templates/common/header.html
<nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('crud.index') }}">
                <span>
                    <img style="width: 24px; height: 24px" alt="藕丝空间" src="{{ url_for('crud.static', filename='images/favicon.png')}}">
                    藕丝空间
                </span>
            </a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="#about">关于</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
</nav><!-- /.navbar -->

flask-wtf-crud-websocket/app/crud/templates/common/sidebar.html
<div class="col-xs-6 col-sm-3 sidebar-offcanvas small pull-right" id="sidebar">
    <ul class="list-group">
        <li class="list-group-item"><a href="{{ url_for('.index') }}" style="color: black">CRUD 主页</a></li>
		 <li class="list-group-item"><a href="{{ url_for('.websocket') }}" style="color: black">CRUD 基本示例</a></li>
		 <li class="list-group-item">Dapibus ac facilisis in</li>
		 <li class="list-group-item">Morbi leo risus</li>
		 <li class="list-group-item">Porta ac consectetur ac</li>
		 <li class="list-group-item">Vestibulum at eros</li>
	</ul>
</div><!--/.sidebar-offcanvas-->

flask-wtf-crud-websocket/app/crud/templates/edit_websocket.html
{% extends 'common/base.html' %}
{% block content %}
<div class="row">
    <div class="col-xs-12 col-sm-offset-2">
        <form method="post" role="form">
            {{ editUserForm.hidden_tag() }}
            <div class="col-xs-12 col-sm-8">              
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i> </span>
                    {{ editUserForm.username(class="form-control", placeholder="用户名",required="", autofocus="") }}
                </div>
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i> </span>
                    {{ editUserForm.email(class="form-control", placeholder="邮 箱", required="") }}
                </div>
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-briefcase"></i> </span>
                    {{ editUserForm.role(class="form-control", required="") }}
                </div>
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-tree-deciduous"></i> </span>
                    {{ editUserForm.status(class="form-control", required="") }}
                </div>
                <div class="modal-footer">
                    <input class="btn btn-default" type="reset" value="重 置">
                    {{ editUserForm.submit(class="btn btn-primary") }}
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock %}

flask-wtf-crud-websocket/app/crud/templates/index.html
{% extends 'common/base.html' %}
{% block content %}
{% endblock %}

flask-wtf-crud-websocket/app/crud/templates/websocket.html
{% extends 'common/base.html' %}
{% block content %}
{% include 'common/alert.html' %}
{% for field_name, field_errors in addUserForm.errors|dictsort if field_errors %}
    {% for error in field_errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{{ addUserForm[field_name].label }}错误：</strong> {{ error }}
        </div>
    {% endfor %}
{% endfor %}
<h3 class="page-header"> CRUD 之 websocket 局部显示示例</h3>
<small id="url_show"></small>
<div id="log"></div>
<table class ="table table-hover">
    <thead>
        <tr>
            <th>序号</th>
            <th>用户名</th>
            <th>邮箱</th>
            <th>权限</th>
            <th>状态</th>
            <th>
                <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target=".bs-example-modal-sm">增加</button>
            </th>
        </tr>
    </thead>
    <tbody class="small" id="users_show">
        <tr>
            {% for user in users %}
                <tr>
                    <th scope="row">{{ loop.index }}</th>
                    <td>{{ user.username}}</td>
                    <td>{{ user.email}}</td>                    
                    {% if user.role %}
                        <td>管理员</td>
                    {% else %}
                        <td>一般用户</td>
                    {% endif %}
                    {% if user.status %}
                        <td>正常</td>
                    {% else %}
                        <td>注销</td>
                    {% endif %}
                    <td><a href="{{ url_for('.user_edit', user_id=user.id) }}"> 修改</a> |
                        <a href="javascript:delete_user_{{ user.id }}()">删除</a>
                        <form method="post" role="form" id="delete_user_{{ user.id }}">
                            {{ deleteUserForm.hidden_tag() }}
                            {{ deleteUserForm.user_id(class="hidden", value=user.id) }}
                        </form>
                        <script type="text/javascript">
                           function delete_user_{{ user.id }}(){
                               $("#delete_user_{{ user.id }}").submit() ;
                           }
                        </script>
                    </td>
                </tr>
                {% endfor %}
        </tr>
    </tbody>
</table>    
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="gridSystemModalLabel">增加信息</h4>
            </div>
            <div class="modal-body">
                <form method="post" role="form">
                    {{ addUserForm.hidden_tag() }}                    
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i> </span>
                        {{ addUserForm.username(class="form-control", placeholder="用户名",required="", autofocus="") }}
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i> </span>
                        {{ addUserForm.email(class="form-control", placeholder="邮 箱", required="") }}
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-briefcase"></i> </span>
                        {{ addUserForm.role(class="form-control", required="") }}
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-tree-deciduous"></i> </span>
                        {{ addUserForm.status(class="form-control", required="") }}
                    </div>
                    <div class="modal-footer">
                        <input class="btn btn-default" type="reset" value="重 置">
                        {{ addUserForm.submit(class="btn btn-primary") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}